description: Github action to run pytest via poetry
name: Run pytest tests from poetry

inputs:
  target-env:
    description: The name of the env to run against e.g. test
    required: true
    type: string

  qe-platform-tag:
    description: The tag of the qe-platform image to pull and run
    required: false
    default: main
    type: string

  pytest-arguments:
    description: The pytest arguments to execute
    required: false
    type: string

runs:
  using: docker
  image: alpine:3.10
  args:
    echo "At the beep it will be..."
