description: Github action to run pytest via poetry
name: Run pytest tests from poetry

inputs:
  target-env:
    description: The name of the env to run against e.g. test
    required: true
    type: string
    defaault: local

  qe-platform-tag:
    description: The tag of the qe-platform image to pull and run
    required: false
    default: main
    type: string

  pytest-arguments:
    description: The pytest arguments to execute
    required: false
    type: string
    default: tests

runs:
  using: composite
  steps:
    - name: Show Inputs Message
      shell: bash
      run: |
        echo "The following inputs have been provided:"
        echo "  target-env: ${{ inputs.target-env }}"
        echo "  qe-platform-tag: ${{ inputs.qe-platform-tag }}"
        echo "  pytest-arguments: ${{ inputs.pytest-arguments }}"
    - name: Run Pytest
      uses: addnab/docker-run-action@v3
      with:
        image: python:3.14.0b3-bullseye
        options: -e INPUTS_TARGET_ENV="${{ inputs.target-env }}" -e INPUTS_QE_PLATFORM_TAG="${{ inputs.qe-platform-tag }}"
        run: |
          python3 -c "import os;run_args=f\"--target-env={os.getenv('INPUTS_TARGET_ENV', 'unknown')}\";print(f\"poetry run pytest {run_args}\")"
          